Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -8,7 +8,7 @@ update_patched_master:
   script:
     - apk --no-cache add git
     - echo "Setting up Git repository locally..."
-    - git clone http://172.17.0.1:4411/haveno/haveno.git /tmp/repo
+    - git clone http://oauth2:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git /tmp/repo
     - cd /tmp/repo
     - echo "Fetching all branches..."
     - git fetch origin
@@ -17,6 +17,9 @@ update_patched_master:
         echo "patched_changes branch found. Proceeding...";
         git checkout patched_master || git checkout -b patched_master;
         git reset --hard origin/patched_changes;
+      else
+        echo "Error: patched_changes branch does not exist in the remote repository.";
+        exit 1;
       fi
     - echo "Force-pushing patched_master to match patched_changes..."
     - git push origin patched_master --force
